apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/stefanprodan/podinfo/kustomize?ref=6.0.3
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: podinfo
  spec:
    template:
      spec:
        containers:
        - name: podinfod
          # https://github.com/stefanprodan/podinfo/pull/164
          image: docker.io/errordeveloper/podinfo:5d3e1398c9f28a7923d466fee38d3f1f92ee81fe
          env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://localhost:4318
