apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo
resources:
  - namespace.yaml
  - https://github.com/istio/istio/raw/1.11.4/samples/bookinfo/platform/kube/bookinfo.yaml
