apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/open-telemetry/opentelemetry-operator/config/default?ref=v0.37.1
images:
- name: controller
  newName: quay.io/opentelemetry/opentelemetry-operator
  newTag: v0.37.1
