apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- github.com/open-telemetry/opentelemetry-operator/config/default?ref=v0.37.1
  # this fork include a fix for cert-manager API versions
  - github.com/errordeveloper/opentelemetry-operator/config/default?ref=8dc2adbe24fb37859c3917e5991a13b551db3e3c
images:
- name: controller
  newName: quay.io/opentelemetry/opentelemetry-operator
  newTag: v0.37.1
