apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # this should normally track ref=v0.37.0, but a specific commit is being used to include https://github.com/open-telemetry/opentelemetry-operator/pull/479;
  # it will need to be updated once v0.38.0 is out
  - github.com/open-telemetry/opentelemetry-operator/config/default
images:
- name: controller
  newName: quay.io/opentelemetry/opentelemetry-operator
  newTag: v0.37.1
